// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShapeServer.DataAccess;

namespace ShapeServer.Migrations
{
    [DbContext(typeof(ShapesDbContext))]
    [Migration("20200912152101_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShapeServer.DataAccess.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Identifier")
                        .HasColumnType("integer");

                    b.Property<List<decimal>>("Parameters")
                        .HasColumnType("numeric[]");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ShapeType")
                        .HasColumnType("integer");

                    b.Property<string>("TreePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("TreePath")
                        .IsUnique();

                    b.ToTable("Shape");
                });

            modelBuilder.Entity("ShapeServer.DataAccess.Models.ShapeEJRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal?>("CurrentArea")
                        .HasColumnType("numeric");

                    b.Property<int>("ShapeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShapeId");

                    b.ToTable("ShapeEJRecord");
                });

            modelBuilder.Entity("ShapeServer.DataAccess.Models.Shape", b =>
                {
                    b.HasOne("ShapeServer.DataAccess.Models.Shape", "Parent")
                        .WithMany("Shapes")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Shape_Shape");
                });

            modelBuilder.Entity("ShapeServer.DataAccess.Models.ShapeEJRecord", b =>
                {
                    b.HasOne("ShapeServer.DataAccess.Models.Shape", "Shape")
                        .WithMany("ShapeEJRecords")
                        .HasForeignKey("ShapeId")
                        .HasConstraintName("FK_ShapeEJRecord_Shape")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
